# -*- coding: utf-8 -*-

env = Environment()   # Create an environmnet
env.Append(CCFLAGS = ['-Wall'])
env.Append(CPPPATH = ['include/vg', 'src'])

libname = 'shivavg'
libsrc = Glob('src/*.c')
         
env.Library(target = libname, source = libsrc)